version: '2'

services:
  js-build:
    image: node:16
    volumes:
      - ./:/code
      - ~/.npm:/npm-cache
    working_dir: /code
    environment:
      - npm_config_cache=/npm-cache
  js-serve:
    extends: js-build
    ports:
      - "8085:8085"
    command: "npm run start"
